CREATE TABLE costumer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   fist_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   income DECIMAL NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zip_code VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   account_free_balance FLOAT,
   balance_blocked FLOAT,
   number_account VARCHAR(255),
   CONSTRAINT pk_costumer PRIMARY KEY (id)
);

ALTER TABLE costumer ADD CONSTRAINT uc_costumer_cpf UNIQUE (cpf);

ALTER TABLE costumer ADD CONSTRAINT uc_costumer_email UNIQUE (email);
