CREATE TABLE account_movement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_id BIGINT,
   date_moviment BIGINT NOT NULL,
   type INT,
   moviment_value FLOAT,
   CONSTRAINT pk_account_movement PRIMARY KEY (id)
);

ALTER TABLE account_movement ADD CONSTRAINT FK_ACCOUNT_MOVEMENT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES costumer (id);