spring:
   datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:credit_application_system_request_db
     username: admin
     password: admin
   jpa:
     show-sql: true
     spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

     #hibernate:
     properties:
       hibernate.format_sql: true

   h2:
     console:
       enabled: true
       path: /h2-console
       setting:
         trace: false
         web-allow-others: false
springdoc:
  swagger-ui:
    path:/swagger-ui.html
